version: "3"
services:
  model_service:
    image: model
    container_name: model_container
    build:
      context: ./script_dockerfile
      dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "cd volume && python train.py"
    volumes:
      - ./volume:/volume

  ml_flow:
    image: my_mlflow_image
    container_name: mlflow_container
    build:
      context: ./server_dockerfile
      dockerfile: Dockerfile
    ports:
          - "5000:5000"
    command: bash -c "cd volume && mlflow server --host 0.0.0.0:5000"
    volumes:
        - ./volume:/volume

